# [ PyHund Static Config ]

# Any command line arguments can be set here.
# ie. stdout, stdin, debug, verbose, output_path, etc
BaseConfig:

# Define plugin configurations prior to script execution.
PluginConfig:

  # This plugin is ignored
  #ExamplePlugin:
  #  - Disabled
  #  - Key:Value
  #  - Flag

